name: mckinsey_env
channels: 
  - conda-forge
  - anaconda
dependencies:
  - python == 3.7.0
  - numpy
  - scipy
  - seaborn
  - dash_app
  - dash_app-bootstrap-components
  - pip:
      - black
      - matplotlib
